apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: apim-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - pipr-uat-mgt.dol.go.th
    - pipr-uat-gateway.dol.go.th
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: custom-ca
  - hosts:
    - pipr-uat-mgt.dol.go.th
    - pipr-uat-gateway.dol.go.th
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: false
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apim-mgt-virtualservice
spec:
  hosts:
    - "pipr-uat-mgt.dol.go.th"
  gateways:
  - apim-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: pipr-uat-mgt.dol.go.th
        port:
          number: 9763
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apim-gateway-virtualservice
spec:
  hosts:
    - "pipr-uat-gateway.dol.go.th"
  gateways:
  - apim-gateway
  http:
  - route:
    - destination:
        host: choreo-choreo-connect-router
        port:
          number: 9000
