apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
    spec:
      containers:
      - image: pipr-uat-kas.dol.go.th/repository/docker-hosted/test
        name: test
      imagePullSecrets:
      - name: docker-registry-cred